[package]
name = "rust-web-poc"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-redis = "0.9.2"
env_logger = "0.8.4"